---

# Debian Ubuntu
- block:
    - name: Add repository apt-key
      apt_key:
        url: "{{ item.key }}"
        state: present
      with_items: "{{ apt_repository_keys }}"
      when: (proxy_env is not defined) or (proxy_env | length < 1)

    - name: Add repository
      apt_repository:
        repo: "{{ item.repo }}"
        state: present
        update_cache: yes
      with_items: "{{ apt_repository }}"
      when: (proxy_env is not defined) or (proxy_env | length < 1)


    - name: Add repository apt-key (behind a proxy)
      apt_key:
        url: "{{ item.key }}"
        state: present
      with_items: "{{ apt_repository_keys }}"
      environment:
        "{{proxy_env}}"
      when: proxy_env | length > 0

    - name: Add repository (behind a proxy)
      apt_repository:
        repo: "{{ item.repo }}"
        state: present
        update_cache: yes
      with_items: "{{ apt_repository }}"
      environment:
        "{{proxy_env}}"
      when: proxy_env | length > 0

  when: ansible_os_family == "Debian"
  tags: add_repo


# RedHat CentOS
- block:
    - name: Add repository
      yum_repository:
        name: "{{ item.name }}"
        description: "{{ item.description }}"
        baseurl: "{{ item.baseurl }}"
        gpgkey: "{{ item.gpgkey }}"
      with_items: "{{ yum_repository }}"
      when: (yum_repository length > 0) and (proxy_env is not defined or proxy_env | length < 1)

    - name: Add repository (behind a proxy)
      yum_repository:
        name: "{{ item.name }}"
        description: "{{ item.description }}"
        baseurl: "{{ item.baseurl }}"
        gpgkey: "{{ item.gpgkey }}"
      with_items: "{{ yum_repository }}"
      environment:
        "{{proxy_env}}"
      when: (yum_repository length > 0) and (proxy_env | length > 0)

  when: ansible_os_family == "RedHat"
  tags: add_repo

