---

# Debian Ubuntu
- block:
    - name: Add repository apt-key
      apt_key:
        url: "{{ item.key }}"
        state: present
      loop: "{{ apt_repository_keys }}"

    - name: Add repository
      apt_repository:
        repo: "{{ item.repo }}"
        state: present
        update_cache: yes
      loop: "{{ apt_repository }}"
  environment: "{{ proxy_env | default(omit) }}"
  when: ansible_os_family == "Debian"
  tags: add_repo

# RedHat CentOS
- block:
    - name: Add repository
      yum_repository:
        name: "{{ item.name }}"
        description: "{{ item.description }}"
        baseurl: "{{ item.baseurl }}"
        gpgkey: "{{ item.gpgkey }}"
      loop: "{{ yum_repository | flatten(1) }}"
      when: yum_repository length > 0

    # Install Epel Repository
    - name: Install | EPEL Repository
      package:
        name: epel-release
      when: install_epel_repo == "true"
      tags: install_epel_repo

    # Install PostgreSQL Repository
    - name: install | get pgdg-redhat-repo-latest.noarch.rpm
      get_url:
        url: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-{{ ansible_distribution_major_version }}-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
        dest: /tmp/
        timeout: 30
        validate_certs: no
      when: install_postgresql_repo == "true"
      tags: install_postgresql_repo

    - name: install | PostgreSQL repository
      package:
        name: /tmp/pgdg-redhat-repo-latest.noarch.rpm
        state: present
      when: install_postgresql_repo == "true"
      tags: install_postgresql_repo
  environment: "{{ proxy_env | default(omit) }}"
  when: ansible_os_family == "RedHat"
  tags: add_repo
