---

- name: PostgreSQL users | make sure the PostgreSQL users are present
  become: yes
  become_user: postgres
  postgresql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    encrypted: "yes"
    login_unix_socket: "{{ postgresql_unix_socket_dir }}"
    port: "{{ postgresql_port }}"
    state: present
  ignore_errors: yes
  with_items: 
    - "{{ postgresql_users }}"
  when: postgresql_users is defined and postgresql_users | length > 0