---
# yamllint disable rule:line-length

# PostgreSQL variables
postgresql_version: "12"  # major version
postgresql_data_dir: "/var/lib/pgpro/std-{{ postgresql_version }}/data"
postgresql_conf_dir: "{{ postgresql_data_dir }}"
postgresql_bin_dir: "/opt/pgpro/std-{{ postgresql_version }}/bin"
postgresql_log_dir: "/var/log/postgresql"
postgresql_unix_socket_dir: "/tmp"
postgresql_home_dir: "/var/lib/pgsql"
postgresql_pgpass: "{{ postgresql_home_dir }}/.pgpass"

# Repository for CentOS7/8
yum_repository:
  - name: "postgrespro-std"
    description: "Postgres Pro Standard repo"
    baseurl: "http://repo.postgrespro.ru//pgpro-archive/pgpro-12.2.1/centos/{{ ansible_distribution_major_version }}/os/x86_64/rpms"
    gpgkey: "http://repo.postgrespro.ru/keys/GPG-KEY-POSTGRESPRO"
    gpgcheck: "yes"

# PostgreSQL packages
postgresql_packages:
  - postgrespro-std-{{ postgresql_version }}-server
  - postgrespro-std-{{ postgresql_version }}-client
  - postgrespro-std-{{ postgresql_version }}-contrib
  - postgrespro-std-{{ postgresql_version }}-devel

# System packages
os_specific_packages:
  RedHat-7:
    - python
    - python-devel
    - python-psycopg2
    - python-setuptools
    - libselinux-python
    - libsemanage-python
    - policycoreutils-python
  RedHat-8:
    - python2  # required for pgbouncer from postgrespro repo
    - python3-libselinux
    - python3-libsemanage
    - python3-policycoreutils
system_packages:
  - python3
  - python3-devel
  - python3-psycopg2
  - python3-setuptools
  - python3-pip
  - "{{ os_specific_packages[ansible_os_family ~ '-' ~ ansible_distribution_major_version] }}"
  - curl
  - less
  - sudo
  - vim
  - gcc
  - jq
  - iptables
  - acl

...
