---

- name: Create systemd unit file io-scheduler.service
  template:
    src: templates/io-scheduler.service.j2
    dest: /etc/systemd/system/io-scheduler.service
  notify: "restart io-scheduler"
  when:
    - set_scheduler is defined
    - set_scheduler == "true"
    - scheduler | length > 0
  tags: scheduler, io_scheduler

- name: Make sure handlers are flushed immediately
  meta: flush_handlers

...
